name: Publish Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Create Dummy Documentation and Diagram
        run: |
          # 1. Creamos la carpeta principal 'docs' y una subcarpeta 'images'
          mkdir -p docs/images

          # 2. Creamos el archivo HTML, pero ahora la imagen apunta a la carpeta 'images'
          echo "<html><head><title>Documentaci칩n</title></head><body><h1>Mi Documentaci칩n</h1><p>Esta es una p치gina de documentaci칩n autogenerada.</p><p>Diagrama de clases (placeholder):</p><img src='images/diagram.svg' alt='Diagrama de Clases'></body></html>" > docs/index.html

          # 3. Creamos el archivo SVG y lo guardamos directamente dentro de la carpeta 'images'
          echo "<svg width='200' height='100'><rect width='200' height='100' style='fill:rgb(200,200,255);stroke-width:3;stroke:rgb(0,0,0)' /><text x='50' y='50' fill='black'>OrderFacade</text></svg>" > docs/images/diagram.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs